django_blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

app_name = 'basic'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_blog.urls')),
    path('user/', include('users.urls')),
]

django_blog/main_blog/urls.py
from django.urls import path
from .views import *
from django_blog import settings
from django.conf.urls.static import static

app_name = 'main_blog'
urlpatterns = [
    path('', AboutProject.as_view(), name='about'),
    path('blog/', GetForMainPage.as_view(), name='blog'),
    path('blog/create_article/', CreateArticle.as_view(), name='create_article'),
    path('blog/article/<slug:art_name>/', GetArticle.as_view(), name='article_name'),
    path('blog/<slug:username>/', GetUserPage.as_view(), name='username'),
]


if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_blog/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'
urlpatterns = [
    path('registration/', RegistrationView.as_view(), name="registration"),
    path('login/', AuthenticationView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
]

django_blog/main_blog/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Category(models.Model):
    name = models.TextField(max_length=100)

    def __str__(self):
        return f"{self.name}"


# Create your models here.
class Article(models.Model):
    slug = models.SlugField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.TextField(max_length=255)
    preview_pic = models.ImageField(upload_to='photos/')
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    category_list = models.ManyToManyField(Category)

    def __str__(self):
        return f"{self.title}"


class Comment(models.Model):
    post = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return f"Comment by {self.author} on {self.post}"


class Followers(models.Model):
    subscriber = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subscriptions')
    subscribed_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subscribers')

    def __str__(self):
        return f"{self.subscriber} subscribe to {self.subscribed_to}"

django_blog/main_blog/forms.py
from django import forms
from .models import Article, Category


class WriteArticleForm(forms.ModelForm):
    preview_pic = forms.ImageField()
    title = forms.CharField(widget=forms.Textarea)
    content = forms.CharField(widget=forms.Textarea)
    category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label="Выберите категорию")
    class Meta:
        model = Article
        fields = ('preview_pic', 'title', 'content', 'category')

django_blog/main_blog/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.contrib.auth import get_user_model, authenticate
from django.urls import reverse
from transliterate import slugify
from .services import get_article_list
from .forms import WriteArticleForm
from .models import Article, Followers, Category, Comment

User = get_user_model()


class GetForMainPage(View):
    """return html template with articles list"""

    def get(self, request):
        selected_category = request.GET.get('category')
        article_list = get_article_list(request, selected_category)
        return render(request, 'main_blog/main_page.html', {"article_list": article_list, "user": request.user})


class GetArticle(View):
    """return html template with article data which taken by 'art_name'"""
    def get(self, request, art_name):
        article = get_object_or_404(Article, slug=art_name)
        comments = Comment.objects.filter(post=article.id)
        return render(request, 'main_blog/article.html', {"article": article, "comments": comments})


class GetUserPage(View):
    """return html template with user profile data which taken by 'username'"""
    def get(self, request, username):
        user = get_object_or_404(User, username__iexact=username)
        followers_count = len(Followers.objects.filter(subscribed_to = user.id))
        written_articles = Article.objects.filter(author=user.id)
        profile_data = {"username": user.username, "first_name": user.first_name,
                        "second_name": user.last_name, "followers_count": followers_count,
                        "written_articles": written_articles}
        return render(request, 'main_blog/profile.html', profile_data)

@method_decorator(login_required(login_url='/user/login'), name='dispatch')
class CreateArticle(View):
    """return html template with form for creating articles"""
    def get(self, request):
        form = WriteArticleForm()
        return render(request, 'main_blog/create_article.html', {"form": form})

    def post(self, request):
        form = WriteArticleForm(request.POST, request.FILES)
        if form.is_valid():
            author = User.objects.get(id=request.user.id)
            title = form.cleaned_data.get('title')
            preview_pic = form.cleaned_data.get('uploaded_photo')
            content = form.cleaned_data.get('content')
            category_list = Category.objects.get(name=form.cleaned_data.get('category')).id
            slug = slugify(title)
            new_article = Article.objects.create(slug=slug, author=author, title=title,
                                                 preview_pic=preview_pic,
                                                 content=content)
            new_article.category_list.set([category_list])
            new_article.save()
            url = reverse('main_blog:blog')
            return HttpResponseRedirect(url)
        else:
            return render(request, 'main_blog/create_article.html', {"form": form})


class AboutProject(View):
    def get(self, request):
        return HttpResponse('page about project')

django_blog/main_blog/templates/main_blog/article.html
{% extends 'main_blog/base.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}
	<div class="container">
		<main>
			<article class="post">
				<header class="post-header">
					<h2>{{article.title}}</h2>
					<p class="post-meta">Опубликовано {{article.pub_date}}</p>
				</header>
				<section class="post-content">
					<p>{{article.content}}</p>
				</section>
			</article>
		</main>
	</div>
{% endblock %}

django_blog/main_blog/templates/main_blog/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'main_blog/css/style.css' %}">
</head>

<body>
    <header>
        <div class="header_section">
            <div class="header__item headerlogo">
                DEPOBLOG
            </div>
            <div class="header__item headerButton"><a href="{% url 'main_blog:about' %}">О проекте</a></div>
            <div class="header__item headerButton"><a href="{% url 'main_blog:blog' %}">Читать статьи</a></div>
        </div>
        <div class="header_section">
            {% if not user.is_authenticated %}
                <div class="header__item headerButton"><a href="{% url 'users:login' %}">Войти</a></div>
                <div class="header__item headerButton"><a href="{% url 'users:registration' %}">Зарегистрироваться</a></div>
            {% else %}
                <div class="header__item headerButton"><a href="{% url 'users:logout' %}">Выйти</a></div>
            {% endif %}
        </div>
    </header>

    {% block content %}{% endblock %}

    <footer>
        место для футера.
    </footer>
</body>
</html>

django_blog/main_blog/templates/main_blog/create_article.html
{% extends 'main_blog/base.html' %}

{% block title %}Напиши стаью{% endblock %}

{% block content %}
    <h1>Место для твоей стаьи</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.errors}}
        <button type="submit">Опубликовать</button>
    </form>
{% endblock %}

django_blog/main_blog/templates/main_blog/main_page.html
{% extends 'main_blog/base.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}
    <div class="article_list">
      {% if article_list %}
          <h1>Список статей</h1>
          {% for article in article_list %}
            <article>
                <div class="article_topic">
                    <h5>Автор:  {{ article.author }}</h5>
                    <h5>Дата публикации:  {{ article.pub_date }}</h5>
                </div>

                <div class="article_photo"></div>

                <div class="artcle_name">
                    {{article.title }}
                </div>
                <div class="article_content">
                    <p>{{ article.content|truncatechars:200 }}</p>
                    <a href="{% url 'main_blog:article_name' art_name=article.slug %}">Читать далее</a>
                </div>
            </article>
          {% endfor %}
      {% else %}
          <h1>Нет доступных статей.</h1>
      {% endif %}
    </div>
{% endblock %}

django_blog/main_blog/templates/main_blog/profile.html
{% extends 'main_blog/base.html' %}

{% block title %}страница пользователя{% endblock %}

{% block content %}
<h3>Никнейм: {{ username }}</h3>
<h3>Имя: {{ first_name }}</h3>
<h3>Фамилия: {{ last_name }}</h3>
<h3>Количество подписчиков: {{ followers_count }}</h3>
{% if written_articles %}
        <h3>Написанные статьи:</h3>
        {% for article in written_articles %}
            <h3><ul>{{ article.title }}</ul></h3>
        {% endfor %}
{% else %}
        <h3>У автора еще нету статей</h3>
{% endif %}
{% endblock %}